//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-10-06T13:03:38Z", "event":"PayBounties", "Amount":500, "Faction":"$faction_Independent;", "Faction_Localised":"Independent", "ShipID":24, "BrokerPercentage":25.000000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_PayBounties : Event_Base
    {
        public Event_PayBounties()
        {
            Name = "PayBounties";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            PayBounties Event = (PayBounties)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Amount", Event.Amount.ToString());
            Variable_Craft("Faction", Event.Faction.ToString());
            Variable_Craft("Faction_Localised", Event.Faction_Localised.ToString());
            Variable_Craft("ShipID", Event.ShipID.ToString());
            Variable_Craft("BrokerPercentage", Event.BrokerPercentage.ToString());
            #endregion
        }
    }

    #region PayBounties Event
    public class PayBounties : Base
    {
        public decimal Amount { get; set; }
        public string Faction { get; set; }
        public string Faction_Localised { get; set; }
        public decimal ShipID { get; set; }
        public decimal BrokerPercentage { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == "PayBounties")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.PayBounties>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
