//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-03T15:26:04Z", "event":"PowerplayVote", "Power":"Edmund Mahon", "Votes":5, "VoteToConsolidate":1 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_PowerplayVote : Event_Base
    {
        public Event_PowerplayVote()
        {
            Name = "PowerplayVote";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            PowerplayVote Event = (PowerplayVote)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Power", Event.Power.ToString());
            Variable_Craft("Votes", Event.Votes.ToString());
            Variable_Craft("VoteToConsolidate", Event.VoteToConsolidate.ToString());
            #endregion
        }
    }

    #region PowerplayVote Event
    public class PowerplayVote : Base
    {
        public string Power { get; set; }
        public decimal Votes { get; set; }
        public decimal VoteToConsolidate { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == "PowerplayVote")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.PowerplayVote>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
