//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-11T23:07:13Z", "event":"NpcCrewRank", "NpcCrewName":"Justine Schwarz", "NpcCrewId":101648352, "RankCombat":1 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_NpcCrewRank : Event_Base
    {
        public Event_NpcCrewRank()
        {
            Name = "NpcCrewRank";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            NpcCrewRank Event = (NpcCrewRank)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("NpcCrewName", Event.NpcCrewName.Variable());
            Variable_Craft("NpcCrewId", Event.NpcCrewId.Variable());
            Variable_Craft("RankCombat", Event.RankCombat.Variable());
            #endregion
        }
    }

    #region NpcCrewRank Event
    public class NpcCrewRank : Base
    {
        public string NpcCrewName { get; set; }
        public decimal NpcCrewId { get; set; }
        public decimal RankCombat { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == NpcCrewRank)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.NpcCrewRank>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
