//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:05:26Z", "event":"Scanned", "ScanType":"Cargo" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Scanned : Event_Base
    {
        public Event_Scanned()
        {
            Name = "Scanned";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Scanned Event = (Scanned)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("ScanType", Event.ScanType.Variable());
            #endregion
        }
    }

    #region Scanned Event
    public class Scanned : Base
    {
        public string ScanType { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == Scanned)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Scanned>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
