//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/20/2018 11:56 PM
//Source Journal Line: { "timestamp":"2018-11-20T22:01:00Z", "event":"SelfDestruct" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Actions;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_SelfDestruct : Event_Base
    {
        public Event_SelfDestruct()
        {
            Name = "SelfDestruct";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //IObjects.Logic_SelfDestruct((SelfDestruct)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SelfDestruct Event = (SelfDestruct)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            #endregion
        }
    }

    #region SelfDestruct Event
    public class SelfDestruct : Base
    {
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "SelfDestruct")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SelfDestruct>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.SelfDestruct.Logic();
// }
