//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-29T00:23:53Z", "event":"Interdicted", "Submitted":true, "Interdictor":"$ShipName_Military_Independent;", "Interdictor_Localised":"System Defence Force", "IsPlayer":false, "Faction":"The Fuel Rats Mischief" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_Interdicted : Event_Base
    {
        public Event_Interdicted()
        {
            Name = "Interdicted";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Process.Interdicted((Interdicted)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Interdicted Event = (Interdicted)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Submitted", Event.Submitted.Variable());
            Variable_Craft("Interdictor", Event.Interdictor.Variable());
            Variable_Craft("Interdictor_Localised", Event.Interdictor_Localised.Variable());
            Variable_Craft("IsPlayer", Event.IsPlayer.Variable());
            Variable_Craft("Faction", Event.Faction.Variable());
            Variable_Craft("CombatRank", Event.CombatRank.Variable());
            #endregion
        }
    }

    #region Interdicted Event
    public class Interdicted : Base
    {
        public bool Submitted { get; set; }
        public string Interdictor { get; set; }
        public string Interdictor_Localised { get; set; }
        public bool IsPlayer { get; set; }
        public string Faction { get; set; }
        public decimal CombatRank { get; set; }

        public Interdicted()
        {
            Submitted = Default.False;
            Interdictor = Default.String;
            Interdictor_Localised = Default.String;
            IsPlayer = Default.False;
            Faction = Default.String;
            CombatRank = Default.Decimal;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == Interdicted)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Interdicted>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
