//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-03T04:20:09Z", "event":"DataScanned", "Type":"ANCIENTCODEX" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_DataScanned : Event_Base
    {
        public Event_DataScanned()
        {
            Name = "DataScanned";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            DataScanned Event = (DataScanned)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Type", Event.Type.Variable());
            #endregion
        }
    }

    #region DataScanned Event
    public class DataScanned : Base
    {
        public string Type { get; set; }

        public DataScanned()
        {
            Type = Default.String;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == DataScanned)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.DataScanned>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
