//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2019-04-23T01:01:07Z", "event":"PayFines", "Amount":100, "AllFines":false, "Faction":"BD+23 296 Blue Federal Inc", "ShipID":11 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class PayFines : Base
    {
        public decimal Amount { get; set; }
        public bool AllFines { get; set; }
        public string Faction { get; set; }
        public decimal ShipID { get; set; }

        //Default Constructor
        public PayFines()
        {
            Amount = Dec();
            AllFines = Bool();
            Faction = Str();
            ShipID = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_PayFines : Event
    {
        //Event Instance
        public PayFines I { get; set; } = new PayFines();

        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                Variables.Record(Name + "_Credits", I.Amount);
                Variables.Record(Name + "_AllFines", I.AllFines);
                Variables.Record(Name + "_Faction", I.Faction);
                Variables.Record(Name + "_ShipID", I.ShipID);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Preparations
        public override void Prepare(object O)
        {
            try
            {
                //Update Event Instance
                I = (PayFines)O;
            }
            catch (Exception ex)
            {
                ExceptionPrepare(Name, ex);
            }
        }
    }
}