//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-28T18:51:15Z", "event":"NpcCrewPaidWage", "NpcCrewName":"Justine Schwarz", "NpcCrewId":101648352, "Amount":1099568 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_NpcCrewPaidWage : Event_Base
    {
        public Event_NpcCrewPaidWage()
        {
            Name = "NpcCrewPaidWage";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            NpcCrewPaidWage Event = (NpcCrewPaidWage)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("NpcCrewName", Event.NpcCrewName.Variable());
            Variable_Craft("NpcCrewId", Event.NpcCrewId.Variable());
            Variable_Craft("Amount", Event.Amount.Variable());
            #endregion
        }
    }

    #region NpcCrewPaidWage Event
    public class NpcCrewPaidWage : Base
    {
        public string NpcCrewName { get; set; }
        public decimal NpcCrewId { get; set; }
        public decimal Amount { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == NpcCrewPaidWage)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.NpcCrewPaidWage>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Bounty.Logic();
// }
