//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T05:19:10Z", "event":"BuyAmmo", "Cost":2139 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_BuyAmmo : Event_Base
    {
        public Event_BuyAmmo()
        {
            Name = "BuyAmmo";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            BuyAmmo Event = (BuyAmmo)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Cost", Event.Cost.Variable());
            #endregion
        }
    }

    #region BuyAmmo Event
    public class BuyAmmo : Base
    {
        public decimal Cost { get; set; }

        public BuyAmmo()
        {
            Cost = Default.Decimal;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == BuyAmmo)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.BuyAmmo>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
