//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T02:31:19Z", "event":"Commander", "Name":"Shadow Doctor K" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_Commander : Event_Base
    {
        public Event_Commander()
        {
            Name = "Commander";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.Commander((Commander)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Commander Event = (Commander)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.Variable());
            #endregion
        }
    }

    #region Commander Event
    public class Commander : Base
    {
        public string Name { get; set; }
        public string FID { get; set; }

        public Commander()
        {
            Name = Default.String;
            FID = Default.String;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == Commander)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Commander>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Commander.Logic();
// }
