//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-28T21:01:59Z", "event":"SendText", "To":"Maddemondog", "Message":"I'll be there shortly. Just helping a beta tester with something real quick. I had to smash a Medium sized bug that only affected people with a fresh install." }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_SendText : Event_Base
    {
        public Event_SendText()
        {
            Name = "SendText";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            SendText Event = (SendText)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("To", Event.To.Variable());
            Variable_Craft("Message", Event.Message.Variable());
            #endregion
        }
    }

    #region SendText Event
    public class SendText : Base
    {
        public string To { get; set; }
        public string Message { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == SendText)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.SendText>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Bounty.Logic();
// }
