//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:16:49Z", "event":"LaunchFighter", "Loadout":"three", "PlayerControlled":false }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_LaunchFighter : Event_Base
    {
        public Event_LaunchFighter()
        {
            Name = "LaunchFighter";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.LaunchFighter((LaunchFighter)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            LaunchFighter Event = (LaunchFighter)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Loadout", Event.Loadout.Variable());
            Variable_Craft("PlayerControlled", Event.PlayerControlled.Variable());
            #endregion
        }
    }

    #region LaunchFighter Event
    public class LaunchFighter : Base
    {
        public string Loadout { get; set; }
        public bool PlayerControlled { get; set; }

        public LaunchFighter()
        {
            Loadout = Default.String;
            PlayerControlled = Default.False;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == LaunchFighter)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.LaunchFighter>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
