//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-14T20:05:33Z", "event":"ApproachBody", "StarSystem":"Col 173 Sector KY-Q d5-47", "SystemAddress":1625603164499, "Body":"Col 173 Sector KY-Q d5-47 8 c", "BodyID":24 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_ApproachBody : Event_Base
    {
        public Event_ApproachBody()
        {
            Name = "ApproachBody";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.ApproachBody((ApproachBody)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ApproachBody Event = (ApproachBody)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StarSystem", Event.StarSystem.Variable());
            Variable_Craft("SystemAddress", Event.SystemAddress.Variable());
            Variable_Craft("Body", Event.Body.Variable());
            Variable_Craft("BodyID", Event.BodyID.Variable());
            #endregion
        }
    }

    #region ApproachBody Event
    public class ApproachBody : Base
    {
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }

        public ApproachBody()
        {
            StarSystem = Default.String;
            SystemAddress = Default.Decimal;
            Body = Default.String;
            BodyID = Default.Decimal;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == ApproachBody)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ApproachBody>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.ApproachBody.Logic();
// }
