//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-02T19:21:27Z", "event":"PowerplayFastTrack", "Power":"Edmund Mahon", "Cost":500000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_PowerplayFastTrack : Event_Base
    {
        public Event_PowerplayFastTrack()
        {
            Name = "PowerplayFastTrack";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            PowerplayFastTrack Event = (PowerplayFastTrack)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Power", Event.Power.ToString());
            Variable_Craft("Cost", Event.Cost.ToString());
            #endregion
        }
    }

    #region PowerplayFastTrack Event
    public class PowerplayFastTrack : Base
    {
        public string Power { get; set; }
        public decimal Cost { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == "PowerplayFastTrack")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.PowerplayFastTrack>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Bounty.Logic();
// }
