//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-29T00:33:24Z", "event":"FactionKillBond", "Reward":59800, "AwardingFaction":"The Fuel Rats Mischief", "VictimFaction":"Constitution Party of Fuelum" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_FactionKillBond : Event_Base
    {
        public Event_FactionKillBond()
        {
            Name = "FactionKillBond";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FactionKillBond Event = (FactionKillBond)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Reward", Event.Reward.Variable());
            Variable_Craft("AwardingFaction", Event.AwardingFaction.Variable());
            Variable_Craft("AwardingFaction_Localised", Event.AwardingFaction_Localised.Variable());
            Variable_Craft("VictimFaction", Event.VictimFaction.Variable());
            Variable_Craft("VictimFaction_Localised", Event.VictimFaction_Localised.Variable());
            #endregion
        }
    }

    #region FactionKillBond Event
    public class FactionKillBond : Base
    {
        public decimal Reward { get; set; }
        public string AwardingFaction { get; set; }
        public string AwardingFaction_Localised { get; set; }
        public string VictimFaction { get; set; }
        public string VictimFaction_Localised { get; set; }

        public FactionKillBond()
        {
            Reward = Default.Decimal;
            AwardingFaction = Default.String;
            AwardingFaction_Localised = Default.String;
            VictimFaction = Default.String;
            VictimFaction_Localised = Default.String;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == FactionKillBond)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FactionKillBond>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
