//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-10-10T19:40:34Z", "event":"MissionAbandoned", "Name":"Mission_DeliveryWing_Boom_name", "MissionID":425090565 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_MissionAbandoned : Event_Base
    {
        public Event_MissionAbandoned()
        {
            Name = "MissionAbandoned";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MissionAbandoned Event = (MissionAbandoned)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Name", Event.Name.ToString());
            Variable_Craft("MissionID", Event.MissionID.ToString());
            #endregion
        }
    }

    #region MissionAbandoned Event
    public class MissionAbandoned : Base
    {
        public string Name { get; set; }
        public decimal MissionID { get; set; }

        public MissionAbandoned()
        {
            Name = Default.String;
            MissionID = Default.Decimal;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == "MissionAbandoned")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MissionAbandoned>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
