//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/22/2018 12:26 AM
//Source Journal Line: { "timestamp":"2018-11-22T03:02:28Z", "event":"MiningRefined", "Type":"$bauxite_name;", "Type_Localised":"Bauxite" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Actions;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_MiningRefined : Event_Base
    {
        public Event_MiningRefined()
        {
            Name = "MiningRefined";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.MiningRefined((MiningRefined)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            MiningRefined Event = (MiningRefined)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Type", Event.Type.ToString());
            Variable_Craft("Type_Localised", Event.Type_Localised.ToString());
            #endregion
        }
    }

    #region MiningRefined Event
    public class MiningRefined : Base
    {
        public string Type { get; set; }
        public string Type_Localised { get; set; }

        public MiningRefined()
        {
            Type = Default.String;
            Type_Localised = Default.String;
        }
    }
    #endregion
}


//Journal Reader Code Chunk.

// else if (EventName == "MiningRefined")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.MiningRefined>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.MiningRefined.Logic();
// }
