//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T05:46:45Z", "event":"Undocked", "StationName":"Morris Barracks", "StationType":"SurfaceStation", "MarketID":3524278272 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_Undocked : Event_Base
    {
        public Event_Undocked()
        {
            Name = "Undocked";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.Undocked((Undocked)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Undocked Event = (Undocked)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("StationName", Event.StationName.Variable());
            Variable_Craft("StationType", Event.StationType.Variable());
            Variable_Craft("MarketID", Event.MarketID.Variable());
            #endregion
        }
    }

    #region Undocked Event
    public class Undocked : Base
    {
        public string StationName { get; set; }
        public string StationType { get; set; }
        public decimal MarketID { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == Undocked)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Undocked>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Bounty.Logic();
// }
