//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-03T03:36:09Z", "event":"LaunchSRV", "Loadout":"starter", "PlayerControlled":true }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_LaunchSRV : Event_Base
    {
        public Event_LaunchSRV()
        {
            Name = "LaunchSRV";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            LaunchSRV Event = (LaunchSRV)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Loadout", Event.Loadout.Variable());
            Variable_Craft("PlayerControlled", Event.PlayerControlled.Variable());
            #endregion
        }
    }

    #region LaunchSRV Event
    public class LaunchSRV : Base
    {
        public string Loadout { get; set; }
        public string PlayerControlled { get; set; }

        public LaunchSRV()
        {
            Loadout = Default.String;
            PlayerControlled = Default.String;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == LaunchSRV)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.LaunchSRV>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
