//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:56:40Z", "event":"FighterRebuilt", "Loadout":"three" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_FighterRebuilt : Event_Base
    {
        public Event_FighterRebuilt()
        {
            Name = "FighterRebuilt";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.FighterRebuilt((FighterRebuilt)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            FighterRebuilt Event = (FighterRebuilt)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Loadout", Event.Loadout.Variable());
            #endregion
        }
    }

    #region FighterRebuilt Event
    public class FighterRebuilt : Base
    {
        public string Loadout { get; set; }

        public FighterRebuilt()
        {
            Loadout = Default.String;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == FighterRebuilt)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.FighterRebuilt>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
