//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:28:34Z", "event":"RebootRepair", "Modules":[  ] }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Ships_Datalink_Interface;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_RebootRepair : Event_Base
    {
        public Event_RebootRepair()
        {
            Name = "RebootRepair";
        }

        public void Logic()
        {
            if (Manager.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            RebootRepair Event = (RebootRepair)Manager.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            //Variable_Craft("Modules", Event.Modules.Variable());
            #endregion
        }
    }

    #region RebootRepair Event
    public class RebootRepair : Base
    {
        public List<string> Modules { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == RebootRepair)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.RebootRepair>(RawLine);
//     Manager.UpdateEvents(EventName, Event);
//     Manager.Bounty.Logic();
// }
