//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-10-05T10:14:08Z", "event":"BuyTradeData", "System":"78 Ursae Majoris", "Cost":100 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_BuyTradeData : Event_Base
    {
        public Event_BuyTradeData()
        {
            Name = "BuyTradeData";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            BuyTradeData Event = (BuyTradeData)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("System", Event.System.ToString());
            Variable_Craft("Cost", Event.Cost.ToString());
            #endregion
        }
    }

    #region BuyTradeData Event
    public class BuyTradeData : Base
    {
        public string System { get; set; }
        public decimal Cost { get; set; }

        public BuyTradeData()
        {
            System = Default.String;
            Cost = Default.Decimal;   
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == "BuyTradeData")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.BuyTradeData>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
