//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-11T19:34:32Z", "event":"Market", "MarketID":3221519616, "StationName":"Rayhan al-Biruni Orbital", "StarSystem":"34 Pegasi" }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_Market : Event_Base
    {
        public Event_Market()
        {
            Name = "Market";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Market Event = (Market)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.Variable());
            Variable_Craft("StationName", Event.StationName.Variable());
            Variable_Craft("StarSystem", Event.StarSystem.Variable());
            #endregion
        }
    }

    #region Market Event
    public class Market : Base
    {
        public decimal MarketID { get; set; }
        public string StationName { get; set; }
        public string StarSystem { get; set; }

        public Market()
        {
            MarketID = Default.Decimal;
            StationName = Default.String;
            StarSystem = Default.String;
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == Market)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.Market>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
