//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-26T10:17:57Z", "event":"CrewHire", "Name":"Korey Cannon", "CrewID":234686432, "Faction":"Eureka Mining Co-Operative", "Cost":15000, "CombatRank":0 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Actions;
using ALICE_Internal;

namespace ALICE_Panels
{
    public class CommsPanel : BasePanel
    {
        public ChatTab Chat { get; set; }
        public InboxTab Inbox { get; set; }
        public SocialTab Social { get; set; }
        public HistoryTab History { get; set; }
        public SquadronTab Squadron { get; set; }
        public SettingsTab Settings { get; set; }

        public CommsPanel()
        {
            Open = false;
            Pos = 1;
            Name = IEnums.Comms;
            Chat = new ChatTab();
            Inbox = new InboxTab();
            Social = new SocialTab();
            History = new HistoryTab();
            Squadron = new SquadronTab();
            Settings = new SettingsTab();
        }

        public class ChatTab : BaseTab
        {
            #region Notes
            //1. Main Chat
            //2 System Chat
            #endregion
          
            public ChatTab()
            {
                Main = 1;
                Tab = 1;
            }

            public bool CheckTab(string MethodName)
            {
                return Check.Panel.Chat(MethodName);
            }

            public bool CheckPanel(string MethodName)
            {
                return Check.Panel.Comms(true, MethodName);
            }

            public override void Panel_Target()
            {
                Call.Panel.Comms.Panel(true);
                Call.Panel.Comms.UpdateTab(Tab);
            }
        }

        public class InboxTab : BaseTab
        {
            #region Notes
            //1. Filter
            //2. - X. Messages
            #endregion

            public InboxTab()
            {
                Main = 1;
                Tab = 2;
            }

            public bool CheckTab(string MethodName)
            {
                return Check.Panel.Inbox(MethodName);
            }

            public bool CheckPanel(string MethodName)
            {
                return Check.Panel.Comms(true, MethodName);
            }

            public override void Panel_Target()
            {
                Call.Panel.Comms.Panel(true);
                Call.Panel.Comms.UpdateTab(Tab);
            }
        }

        public class SocialTab : BaseTab
        {
            public SocialTab()
            {
                Tab = 3;
            }

            public bool CheckTab(string MethodName)
            {
                return Check.Panel.Social(MethodName);
            }

            public bool CheckPanel(string MethodName)
            {
                return Check.Panel.Comms(true, MethodName);
            }

            public override void Panel_Target()
            {
                Call.Panel.Comms.Panel(true);
                Call.Panel.Comms.UpdateTab(Tab);
            }
        }

        public class HistoryTab : BaseTab
        {
            public HistoryTab()
            {
                Tab = 4;
            }

            public bool CheckTab(string MethodName)
            {
                return Check.Panel.History(MethodName);
            }

            public bool CheckPanel(string MethodName)
            {
                return Check.Panel.Comms(true, MethodName);
            }

            public override void Panel_Target()
            {
                Call.Panel.Comms.Panel(true);
                Call.Panel.Comms.UpdateTab(Tab);
            }
        }

        public class SquadronTab : BaseTab
        {
            public SquadronTab()
            {
                Tab = 5;
            }

            public bool CheckTab(string MethodName)
            {
                return Check.Panel.Squadron(MethodName);
            }

            public bool CheckPanel(string MethodName)
            {
                return Check.Panel.Comms(true, MethodName);
            }

            public override void Panel_Target()
            {
                Call.Panel.Comms.Panel(true);
                Call.Panel.Comms.UpdateTab(Tab);
            }
        }

        public class SettingsTab : BaseTab
        {
            public SettingsTab()
            {
                Tab = 6;
            }

            public bool CheckTab(string MethodName)
            {
                return Check.Panel.Settings(MethodName);
            }

            public bool CheckPanel(string MethodName)
            {
                return Check.Panel.Comms(true, MethodName);
            }

            public override void Panel_Target()
            {
                Call.Panel.Comms.Panel(true);
                Call.Panel.Comms.UpdateTab(Tab);
            }
        }
    }
}
