//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-10-05T10:14:08Z", "event":"BuyTradeData", "System":"78 Ursae Majoris", "Cost":100 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class BuyTradeData : Base
    {
        public string System { get; set; }
        public decimal Cost { get; set; }

        //Default Constructor
        public BuyTradeData()
        {
            System = Str();
            Cost = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_BuyTradeData : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (BuyTradeData)O;

                Variables.Record(Name + "_System", Event.System);
                Variables.Record(Name + "_Cost", Event.Cost);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}
