//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-10-30T23:18:10Z", "event":"SetUserShipName", "Ship":"typex", "ShipID":59, "UserShipName":"Collossus of the fall", "UserShipId":"AG-30T" }

using ALICE_Objects;
using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class SetUserShipName : Base
    {
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
        public string UserShipName { get; set; }    //New Name
        public string UserShipId { get; set; }      //Custom Identifier

        //Default Constructor
        public SetUserShipName()
        {
            Ship = Str();
            ShipID = Dec();
            UserShipName = Str();
            UserShipId = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_SetUserShipName : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (SetUserShipName)O;

                Variables.Record(Name + "_Ship", Event.Ship);
                Variables.Record(Name + "_ID", Event.ShipID);
                Variables.Record(Name + "_ShipName", Event.ShipID);
                Variables.Record(Name + "_CallSign", Event.UserShipId);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (SetUserShipName)O;

                //Update Mothership Data
                IStatus.Mothership.Update(Event);
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}