//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/21/2018 8:14 PM
//Source Journal Line: { "timestamp":"2018-11-22T01:13:15Z", "event":"FSDTarget", "Name":"NGC 2451A Sector DW-M b7-9", "SystemAddress":20472632452441 }

using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class FSDTarget : Base
    {
        public string Name { get; set; }
        public decimal SystemAddress { get; set; }

        //Default Constructor
        public FSDTarget()
        {
            Name = Str();
            SystemAddress = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_FSDTarget : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (FSDTarget)O;

                Variables.Record(Name + "_System", Event.Name);
                Variables.Record(Name + "_Address", Event.SystemAddress);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (FSDTarget)O;

                //Update Status Object
                IStatus.System.Update(Event);
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}