//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-29T01:05:53Z", "event":"MissionRedirected", "MissionID":429329381, "Name":"Mission_Massacre_Conflict_War_name", "NewDestinationStation":"Wollheim Vision", "NewDestinationSystem":"Fuelum", "OldDestinationStation":"", "OldDestinationSystem":"Fuelum" }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class MissionRedirected : Base
    {
        public string Name { get; set; }
        public decimal MissionID { get; set; }
        public string NewDestinationStation { get; set; }
        public string NewDestinationSystem { get; set; }
        public string OldDestinationStation { get; set; }
        public string OldDestinationSystem { get; set; }

        //Default Constructor
        public MissionRedirected()
        {
            Name = Str();
            MissionID = Dec();
            NewDestinationStation = Str();
            NewDestinationSystem = Str();
            OldDestinationStation = Str();
            OldDestinationSystem = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_MissionRedirected : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (MissionRedirected)O;

                Variables.Record(Name + "_Name", Event.Name);
                Variables.Record(Name + "_ID", Event.MissionID);
                Variables.Record(Name + "_NewSystem", Event.NewDestinationSystem);
                Variables.Record(Name + "_NewStation", Event.NewDestinationStation);
                Variables.Record(Name + "_OldSystem", Event.OldDestinationSystem);
                Variables.Record(Name + "_OldStation", Event.OldDestinationStation);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}