//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-08T20:29:40Z", "event":"SellExplorationData", "Systems":[ "IC 2391 Sector BA-A d94", "IC 2391 Sector AQ-Y c12", "IC 2391 Sector EL-Y c12", "Synuefe AN-H d11-99", "IC 2391 Sector CA-A d99", "Cairne", "Synuefe XP-N c23-13", "Synuefe YP-N c23-13", "Erlaza", "Synuefe ZP-N c23-14", "Synuefe BZ-Q c21-14", "LFT 1", "LHS 2447", "Synuefe YP-N c23-16", "Lu Yupik", "Col 285 Sector KW-M c7-18", "ICZ ZK-X b1-2", "CD-56 1032", "LP 915-27", "Col 285 Sector DP-X b15-2", "Synuefe ZG-Z b47-2", "Synuefe WQ-Z b47-2", "Synuefe BH-Z b47-2", "IC 2391 Sector CG-X b1-2", "Synuefe CE-G b44-2", "Synuefe KQ-C b46-2", "Synuefe BY-H b43-2", "Synuefe IZ-F b44-2", "Synuefe AW-L c24-19", "Piscium Sector JY-H a10-0", "Tascheter Sector JX-K a8-0", "Puppis Sector BW-N a6-0", "ICZ BQ-Y c21", "Synuefe ZP-N c23-21", "Swaza", "Synuefe ZE-P c22-23", "IC 2391 Sector EL-Y c23", "Synuefe YY-Q c21-23", "ICZ CV-Y c24", "Synuefe VP-N c23-25", "Ceti Sector SE-Q b5-3", "ICZ CG-X b1-3", "LHS 17", "Ross 854", "Col 285 Sector SJ-W b16-3", "Bunus", "Col 285 Sector XI-Z b14-3", "Synuefe ZG-Z b47-3", "Synuefe YU-C b46-3" ], "Discovered":[  ], "BaseValue":918412, "Bonus":0, "TotalEarnings":789872 }

using System;
using System.Collections.Generic;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class SellExplorationData : Base
    {
        public List<string> Systems { get; set; }
        public List<string> Discovered { get; set; }
        public decimal BaseValue { get; set; }
        public decimal Bonus { get; set; }
        public decimal TotalEarnings { get; set; }

        //Default Constructor
        public SellExplorationData()
        {
            Systems = new List<string>();
            Discovered = new List<string>();
            BaseValue = Dec();
            Bonus = Dec();
            TotalEarnings = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_SellExplorationData : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (SellExplorationData)O;

                Variables.Record(Name + "_BaseCredits", Event.BaseValue);
                Variables.Record(Name + "_BonusCredits", Event.Bonus);
                Variables.Record(Name + "_TotalCredits", Event.TotalEarnings);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}