//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-10-06T09:26:51Z", "event":"DatalinkVoucher", "Reward":13808, "VictimFaction":"Alliance", "PayeeFaction":"Federation" }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class DatalinkVoucher : Base
    {
        public decimal Reward { get; set; }
        public string VictimFaction { get; set; }
        public string PayeeFaction { get; set; }

        //Default Constructor
        public DatalinkVoucher()
        {
            Reward = Dec();
            VictimFaction = Str();
            PayeeFaction = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_DatalinkVoucher : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (DatalinkVoucher)O;

                Variables.Record(Name + "_Reward", Event.Reward);
                Variables.Record(Name + "_Victim", Event.VictimFaction);
                Variables.Record(Name + "_Payee", Event.PayeeFaction);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}