//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:19:19Z", "event":"HullDamage", "Health":0.728289, "PlayerPilot":false, "Fighter":true }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class HullDamage : Base
    {
        public decimal Health { get; set; }
        public bool PlayerPilot { get; set; }
        public bool Fighter { get; set; }

        //Default Constructor
        public HullDamage()
        {
            Health = Dec();
            PlayerPilot = Bool();
            Fighter = Bool();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_HullDamage : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (HullDamage)O;

                Variables.Record(Name + "_Health", Event.Health);
                Variables.Switch(Name + "_Pilot", Event.PlayerPilot, "Commander", "NPC");
                Variables.Switch(Name + "_Vehicle", Event.PlayerPilot, "Fighter", "Mothership");
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}