//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-02T20:06:42Z", "event":"BuyExplorationData", "System":"Fong Dadia", "Cost":6897 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class BuyExplorationData : Base
    {
        public string System { get; set; }
        public decimal Cost { get; set; }

        //Default Constructor
        public BuyExplorationData()
        {
            System = Str();
            Cost = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_BuyExplorationData : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (BuyExplorationData)O;

                Variables.Record(Name + "_System", Event.System);
                Variables.Record(Name + "_Cost", Event.Cost);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}