//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:17:19Z", "event":"UnderAttack", "Target":"You" }

using ALICE_Core;
using ALICE_Objects;
using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class UnderAttack : Base
    {
        public string Target { get; set; }

        //Default Constructor
        public UnderAttack()
        {
            Target = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_UnderAttack : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (UnderAttack)O;

                //Define Commander Or NPC
                Variables.Switch(Name + "_Target", Event.Target.Contains("You"), "Commander", "NPC");

                //Define Vehicle
                if (Event.Target.Contains("You"))
                {
                    Variables.Record(Name + "_Vehicle", IStatus.Vehicle.ToString());
                }
                else
                {
                    Variables.Record(Name + "_Vehicle", Event.Target);
                }
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment(object O)
        {
            try
            {
                //Disable Weapons Safeies Incase We Are Inside The No Fire Zone                
                IStatus.WeaponSafety = false;
                IStatus.Hyperspace = false;
                IStatus.Supercruise = false;
            }
            catch (Exception ex)
            {
                ExceptionAlignment(Name, ex);
            }
        }
    }
}