//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-08T19:58:41Z", "event":"HeatWarning" }

using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class HeatWarning : Base
    {
        //No Properties
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_HeatWarning : Event
    {
        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (HeatWarning)O;

                //Update Status Object
                IStatus.Heat.Update(Event);
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}