//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/21/2018 10:32 PM
//Source Journal Line: { "timestamp":"2018-11-22T02:49:58Z", "event":"SAAScanComplete", "BodyName":"HR 8514 4", "BodyID":20, "ProbesUsed":12, "EfficiencyTarget":9 }

using ALICE_Objects;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class SAAScanComplete : Base
    {
        public string BodyName { get; set; }
        public decimal BodyID { get; set; }
        public decimal ProbesUsed { get; set; }
        public decimal EfficiencyTarget { get; set; }

        //Default Constructor
        public SAAScanComplete()
        {
            BodyName = Str();
            BodyID = Dec();
            ProbesUsed = Dec();
            EfficiencyTarget = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_SAAScanComplete : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (SAAScanComplete)O;

                Variables.Record(Name + "_Name", Event.BodyName);
                Variables.Record(Name + "_ID", Event.BodyID);
                Variables.Record(Name + "_Probes", Event.ProbesUsed);
                Variables.Record(Name + "_EfficiencyTarget", Event.EfficiencyTarget);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (SAAScanComplete)O;

                //Update Current System Objects
                IObjects.SystemCurrent.Update_StellarBody(Event);

                //Extended Logger
                IObjects.SystemCurrent.Log_SystemBodies();
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}