//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T04:05:26Z", "event":"Scanned", "ScanType":"Cargo" }

using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class Scanned : Base
    {
        public string ScanType { get; set; }

        //Default Constructor
        public Scanned()
        {
            ScanType = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_Scanned : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (Scanned)O;

                Variables.Record(Name + "_Type", Event.ScanType);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (Scanned)O;

                //Update Status Object
                IStatus.Scanned.Update(Event);
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}