//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T05:19:58Z", "event":"SellDrones", "Type":"Drones", "Count":19, "SellPrice":100, "TotalSale":1900 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class SellDrones : Base
    {
        public string Type { get; set; }
        public decimal Count { get; set; }
        public decimal SellPrice { get; set; }
        public decimal TotalSale { get; set; }

        //Default Constructor
        public SellDrones()
        {
            Type = Str();
            Count = Dec();
            SellPrice = Dec();
            TotalSale = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_SellDrones : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (SellDrones)O;

                Variables.Record(Name + "_Type", Event.Type);
                Variables.Record(Name + "_Count", Event.Count);
                Variables.Record(Name + "_SellPrice", Event.SellPrice);
                Variables.Record(Name + "_Cost", Event.TotalSale);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}