//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-22T01:01:36Z", "event":"EjectCargo", "Type":"consumertechnology", "Type_Localised":"Consumer Technology", "Count":1, "Abandoned":false }

using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class EjectCargo : Base
    {
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public decimal Count { get; set; }
        public string Abandoned { get; set; }

        //Default Constructor
        public EjectCargo()
        {
            Type = Str();
            Type_Localised = Str();
            Count = Dec();
            Abandoned = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_EjectCargo : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (EjectCargo)O;

                Variables.Record(Name + "_Name", Event.Type_Localised);
                Variables.Record(Name + "_EDName", Event.Type);
                Variables.Record(Name + "_Count", Event.Count);
                Variables.Record(Name + "_Abandoned", Event.Abandoned);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment(object O)
        {
            try
            {
                IStatus.Hyperspace = false;
            }
            catch (Exception ex)
            {
                ExceptionAlignment(Name, ex);
            }
        }
    }
}
