//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-02T19:21:27Z", "event":"PowerplayFastTrack", "Power":"Edmund Mahon", "Cost":500000 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class PowerplayFastTrack : Base
    {
        public string Power { get; set; }
        public decimal Cost { get; set; }

        //Default Constructor
        public PowerplayFastTrack()
        {
            Power = Str();
            Cost = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_PowerplayFastTrack : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (PowerplayFastTrack)O;

                Variables.Record(Name + "_Power", Event.Power);
                Variables.Record(Name + "_Cost", Event.Cost);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}
