//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T03:42:53Z", "event":"ModuleRetrieve", "MarketID":3221503744, "Slot":"Slot07_Size5", "RetrievedItem":"$int_hullreinforcement_size5_class2_name;", "RetrievedItem_Localised":"Hull Reinforcement", "Ship":"federation_corvette", "ShipID":11, "Hot":false, "EngineerModifications":"HullReinforcement_HeavyDuty", "Level":3, "Quality":0.000000, "SwapOutItem":"$int_stellarbodydiscoveryscanner_advanced_name;", "SwapOutItem_Localised":"D - Scanner" }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ModuleRetrieve : Base
    {
        public decimal MarketID { get; set; }
        public string Slot { get; set; }
        public string RetrievedItem { get; set; }
        public string RetrievedItem_Localised { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
        public bool Hot { get; set; }
        public string EngineerModifications { get; set; }
        public decimal Level { get; set; }
        public decimal Quality { get; set; }
        public string SwapOutItem { get; set; }
        public string SwapOutItem_Localised { get; set; }

        //Default Constructor
        public ModuleRetrieve()
        {
            MarketID = Dec();
            Slot = Str();
            RetrievedItem = Str();
            RetrievedItem_Localised = Str();
            Ship = Str();
            ShipID = Dec();
            Hot = Bool();
            EngineerModifications = Str();
            Level = Dec();
            Quality = Dec();
            SwapOutItem = Str();
            SwapOutItem_Localised = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_ModuleRetrieve : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (ModuleRetrieve)O;

                Variables.Record(Name + "_MarketID", Event.MarketID);
                Variables.Record(Name + "_Slot", GetSlot(Event.Slot, false));
                Variables.Switch(Name + "_RetrievedItem", Event.RetrievedItem_Localised, Event.RetrievedItem);
                Variables.Record(Name + "_Ship", Event.Ship);
                Variables.Record(Name + "_ShipID", Event.ShipID);
                Variables.Record(Name + "_Hot", Event.Hot);
                Variables.Record(Name + "_Modifications", Event.EngineerModifications);
                Variables.Record(Name + "_Level", Event.Level);
                Variables.Record(Name + "_Quality", Event.Quality);                
                Variables.Switch(Name + "_SwapOutItem", Event.SwapOutItem_Localised, Event.SwapOutItem);                
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}