//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-23T14:08:18Z", "event":"PowerplayCollect", "Power":"Edmund Mahon", "Type":"$alliancelegaslativerecords_name;", "Type_Localised":"Alliance Legislative Records", "Count":50 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class PowerplayCollect : Base
    {
        public string Power { get; set; }
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public decimal Count { get; set; }

        //Default Constructor
        public PowerplayCollect()
        {
            Power = Str();
            Type = Str();
            Type_Localised = Str();
            Count = Dec();            
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_PowerplayCollect : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (PowerplayCollect)O;

                Variables.Record(Name + "_Power", Event.Power);
                Variables.Record(Name + "_Type", Event.Type_Localised);
                Variables.Record(Name + "_Count", Event.Count);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}