//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-17T08:01:25Z", "event":"USSDrop", "USSType":"$USS_Type_VeryValuableSalvage;", "USSType_Localised":"High grade emissions detected", "USSThreat":0 }

using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class USSDrop : Base
    {
        public string USSType { get; set; }
        public string USSType_Localised { get; set; }
        public decimal USSThreat { get; set; }

        //Default Constructor
        public USSDrop()
        {
            USSType = Str();
            USSType_Localised = Str();
            USSThreat = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_USSDrop : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (USSDrop)O;
                
                Variables.Switch(Name + "_Type", Event.USSType_Localised, Event.USSType);
                Variables.Record(Name + "_Threat", Event.USSThreat);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment(object O)
        {
            try
            {             
                IStatus.WeaponSafety = false;                
            }
            catch (Exception ex)
            {
                ExceptionAlignment(Name, ex);
            }
        }
    }
}