//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 4:40 PM
//Source Journal Line: { "timestamp":"2018-09-20T13:20:16Z", "event":"Repair", "Item":"Wear", "Cost":52160 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class Repair : Base
    {
        public string Item { get; set; }
        public string Item_Localised { get; set; }
        public decimal Cost { get; set; }

        //Default Constructor
        public Repair()
        {
            Item = Str();
            Item_Localised = Str();
            Cost = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_Repair : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (Repair)O;

                Variables.Switch(Name + "_Item", Event.Item_Localised, Event.Item);
                Variables.Record(Name + "_Credits", Event.Cost);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}