//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-02T05:19:10Z", "event":"BuyAmmo", "Cost":2139 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class BuyAmmo : Base
    {
        public decimal Cost { get; set; }

        //Default Constructor
        public BuyAmmo()
        {
            Cost = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_BuyAmmo : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (BuyAmmo)O;

                Variables.Record(Name + "_Cost", Event.Cost);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }
    }
}
