//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALICE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Filters : global::System.Configuration.ApplicationSettingsBase {
        
        private static Filters defaultInstance = ((Filters)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Filters())));
        
        public static Filters Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_Cargo_Damaging {
            get {
                return ((bool)(this["Filter_Cargo_Damaging"]));
            }
            set {
                this["Filter_Cargo_Damaging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_Cargo_Illegal {
            get {
                return ((bool)(this["Filter_Cargo_Illegal"]));
            }
            set {
                this["Filter_Cargo_Illegal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_Cargo_Mission {
            get {
                return ((bool)(this["Filter_Cargo_Mission"]));
            }
            set {
                this["Filter_Cargo_Mission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_Cargo_PowerPlay {
            get {
                return ((bool)(this["Filter_Cargo_PowerPlay"]));
            }
            set {
                this["Filter_Cargo_PowerPlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Filter_Cargo_Stolen {
            get {
                return ((bool)(this["Filter_Cargo_Stolen"]));
            }
            set {
                this["Filter_Cargo_Stolen"] = value;
            }
        }
    }
}
