//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALICE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Plugin : global::System.Configuration.ApplicationSettingsBase {
        
        private static Plugin defaultInstance = ((Plugin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Plugin())));
        
        public static Plugin Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sleep_PanelSpeed {
            get {
                return ((int)(this["Sleep_PanelSpeed"]));
            }
            set {
                this["Sleep_PanelSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sleep_PipSpeed {
            get {
                return ((int)(this["Sleep_PipSpeed"]));
            }
            set {
                this["Sleep_PipSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sleep_FireGroupSpeed {
            get {
                return ((int)(this["Sleep_FireGroupSpeed"]));
            }
            set {
                this["Sleep_FireGroupSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Sleep_ThrottleSpeed {
            get {
                return ((int)(this["Sleep_ThrottleSpeed"]));
            }
            set {
                this["Sleep_ThrottleSpeed"] = value;
            }
        }
    }
}
