//Code Generated By: CMDR Shadow Doctor K
//Class File Generated: 02/24/2019 5:24 PM
//Source Journal Line: (Custom A.L.I.C.E Event)
//Reference Journal Line:

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class Templet : Base
    {
        //No Properties

        //Default Constructor
        public Templet()
        {

        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_Templet : Event
    {
        //Event Instance
        public Templet I = new Templet();

        //Construct Event
        public void Contstruct()
        {

        }

        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                //Variables.Record(Name + "_Type", Event.Type);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Preparations
        public override void Prepare(object O)
        {
            try
            {
                //No Preparations
            }
            catch (Exception ex)
            {
                ExceptionPrepare(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                //No Logic Process
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment(object O)
        {
            try
            {
                //No Updates
            }
            catch (Exception ex)
            {
                ExceptionAlignment(Name, ex);
            }
        }
    }
}