//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-11T20:57:31Z", "event":"CommitCrime", "CrimeType":"collidedAtSpeedInNoFireZone_hulldamage", "Faction":"Eureka Mining Co-Operative", "Fine":100 }
//Reference Journal Line: { "timestamp":"2018-11-22T01:47:10Z", "event":"CommitCrime", "CrimeType":"dockingMinorBlockingAirlock", "Faction":"Eureka Mining Co-Operative", "Fine":300 }
//Reference Journal Line: { "timestamp":"2018-11-22T01:47:55Z", "event":"CommitCrime", "CrimeType":"dockingMinorBlockingLandingPad", "Faction":"Eureka Mining Co-Operative", "Fine":300 }

using ALICE_Core;
using ALICE_Internal;
using ALICE_Synthesizer;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_CommitCrime : Base
    {
        public string CrimeType { get; set; }
        public string Faction { get; set; }
        public string Victim { get; set; }
        public string Victim_Localised { get; set; }
        public decimal Fine { get; set; }
        public decimal Bounty { get; set; }

        //Default Constructor
        public ASDF_CommitCrime()
        {
            CrimeType = Str();
            Faction = Str();
            Victim = Str();
            Victim_Localised = Str();
            Fine = Dec();
            Bounty = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_CommitCrime : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (CommitCrime)O;

                Variables.Record(Name + "_Crime", Event.CrimeType);
                Variables.Record(Name + "_Faction", Event.Faction);
                Variables.Record(Name + "_Victim", Event.Victim_Localised);

                switch (Variables.Switch(Name + "_Credits", Event.Fine, Event.Bounty))
                {
                    case true: Variables.Record(Name + "_Charge", "Fine"); break;
                    case false: Variables.Record(Name + "_Charge", "Bounty"); break;
                }
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (CommitCrime)O;

                //Convert String To Enum
                IEnums.CrimeType Crime = IEnums.ToEnum<IEnums.CrimeType>(Event.CrimeType, false);

                //Evaluate Crime Type
                switch (Crime)
                {
                    case IEnums.CrimeType.Assault:

                        //Construct Assult Event
                        IEvents.Assult.Construct(Event); break;

                    case IEnums.CrimeType.MinorBlockingAirlock:

                        //IEvents.BlockAirlock.Construct(Event);
                        break;
                    case IEnums.CrimeType.MajorBlockingAirlock:

                        //IEvents.BlockAirlock.Construct(Event);
                        break;

                    case IEnums.CrimeType.MinorBlockingLandingPad:

                        //IEvents.BlockLandingPadMinor.Construct(Event);
                        break;
                    case IEnums.CrimeType.MajorBlockingLandingPad:

                        //IEvents.BlockLandingPadMajor.Construct(Event);
                        break;
                    case IEnums.CrimeType.FireInNoFireZone:

                        //IEvents.FireInNoFireZone.Construct(Event);
                        break;
                    case IEnums.CrimeType.Murder:

                        //IEvents.Murder.Construct(Event);
                        break;
                    case IEnums.CrimeType.Piracy:

                        break;
                    case IEnums.CrimeType.Interdicting:

                        break;
                    case IEnums.CrimeType.IllegalCargo:

                        break;
                    case IEnums.CrimeType.DisobeyPolice:

                        break;
                    case IEnums.CrimeType.FireInStation:

                        //IEvents.FireInStation.Construct(Event);
                        break;
                    case IEnums.CrimeType.DumpingDangerous:

                        break;
                    case IEnums.CrimeType.DumpingNearStation:

                        break;
                    case IEnums.CrimeType.DockingMinor_Trespass:

                        break;
                    case IEnums.CrimeType.DockingMajor_Trespass:

                        break;
                    case IEnums.CrimeType.CollidedAtSpeedInNoFireZone:

                        break;
                    case IEnums.CrimeType.CollidedAtSpeedInNoFireZone_HullDamage:

                        break;

                    default:

                        //Audio - Generic Crime
                        IStatus.Crime.Response.Generic(
                            Check.Internal.TriggerEvents(true, ClassName));     //Check Plugin Initialized

                        //Record New Items To Developer Log
                        Logger.DeveloperLog("Developer Record: [CommitCrime:CrimeType] " + Event.CrimeType);
                        break;
                }
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}
