//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-19T03:47:33Z", "event":"BuyDrones", "Type":"Drones", "Count":108, "BuyPrice":101, "TotalCost":10908 }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_BuyDrones : Base
    {
        public string Type { get; set; }
        public decimal Count { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal TotalCost { get; set; }

        //Default Constructor
        public ASDF_BuyDrones()
        {
            Type = Str();
            Count = Dec();
            BuyPrice = Dec();
            TotalCost = Dec();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_BuyDrones : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (BuyDrones)O;

                Variables.Record(Name + "_Type", Event.Type);
                Variables.Record(Name + "_Count", Event.Count);
                Variables.Record(Name + "_Cost", Event.TotalCost);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (BuyDrones)O;
            }
            catch (Exception ex)
            {
                ExceptionProcess(ex);
            }
        }
    }
}