//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-14T05:29:24Z", "event":"CollectCargo", "Type":"ancientcasket", "Type_Localised":"Ancient Casket", "Stolen":false }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_CollectCargo : Base
    {
        public string Type { get; set; }
        public string Type_Localised { get; set; }
        public string Stolen { get; set; }

        //Default Constructor
        public ASDF_CollectCargo()
        {
            Type = Str();
            Type_Localised = Str();
            Stolen = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_CollectCargo : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (CollectCargo)O;

                Variables.Record(Name + "_Name", Event.Type_Localised);
                Variables.Record(Name + "_Stolen", Event.Stolen);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (CollectCargo)O;
            }
            catch (Exception ex)
            {
                ExceptionProcess(ex);
            }
        }
    }
}