//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/20/2018 11:56 PM
//Source Journal Line: { "timestamp":"2018-11-20T22:01:00Z", "event":"ChangeCrewRole", "Role":"FireCon" }

using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_ChangeCrewRole : Base
    {
        public string Role { get; set; }

        //Default Constructor
        public ASDF_ChangeCrewRole()
        {
            Role = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_ChangeCrewRole : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (ChangeCrewRole)O;

                Variables.Record(Name + "_Role", Event.Role);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (ChangeCrewRole)O;
            }
            catch (Exception ex)
            {
                ExceptionProcess(ex);
            }
        }
    }
}
