//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-03T03:36:09Z", "event":"LaunchSRV", "Loadout":"starter", "PlayerControlled":true }

using ALICE_Core;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_LaunchSRV : Base
    {
        public string Loadout { get; set; }
        public bool PlayerControlled { get; set; }

        //Default Constructor
        public ASDF_LaunchSRV()
        {
            Loadout = Str();
            PlayerControlled = Bool();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_LaunchSRV : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (LaunchSRV)O;

                Variables.Record(Name + "_Loadout", Event.Loadout);
                Variables.Switch(Name + "_Pilot", Event.PlayerControlled, "Commander", "NPC");
            }
            catch (Exception ex)
            {
                ExceptionGenerate(ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (LaunchSRV)O;
            }
            catch (Exception ex)
            {
                ExceptionProcess(ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment()
        {
            IStatus.Touchdown = true;
            IStatus.LandingGear = true;
            IStatus.Supercruise = false;
            IStatus.Hyperspace = false;
            IStatus.Docking.Docked = false;
        }
    }
}