//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-14T20:07:57Z", "event":"SupercruiseExit", "StarSystem":"Col 173 Sector KY-Q d5-47", "SystemAddress":1625603164499, "Body":"Col 173 Sector KY-Q d5-47 8 c", "BodyID":24, "BodyType":"Planet" }

using ALICE_Actions;
using ALICE_Core;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_SupercruiseExit : Base
    {
        public string StarSystem { get; set; }
        public decimal SystemAddress { get; set; }
        public string Body { get; set; }
        public decimal BodyID { get; set; }
        public string BodyType { get; set; }

        //Default Constructor
        public ASDF_SupercruiseExit()
        {
            StarSystem = Str();
            SystemAddress = Dec();
            Body = Str();
            BodyID = Dec();
            BodyType = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_SupercruiseExit : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (SupercruiseExit)O;

                Variables.Record(Name + "_System", Event.StarSystem);
                Variables.Record(Name + "_Address", Event.SystemAddress);
                Variables.Record(Name + "_Body", Event.Body);
                Variables.Record(Name + "_ID", Event.BodyID);
                Variables.Record(Name + "_Type", Event.BodyType);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(Name, ex);
            }
        }

        //Plugin Logic Preparations
        public override void Prepare(object O)
        {
            try
            {
                IEquipment.FrameShiftDrive.Reset();
                IEquipment.FrameShiftDrive.Disengaging = false;
                IEvents.FireInNoFireZone.FirstReport = true;
                Call.Panel.MainFourIsFalse();
            }
            catch (Exception ex)
            {
                ExceptionPrepare(Name, ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (SupercruiseExit)O;                

                //Update Status Object
                IStatus.Docking.Update(Event);

                //Assisted Docking Procedure
                IStatus.Docking.AssistedDocking(Event);

                //Glide Monitor
                IStatus.Planet.Glide(Event);

                //Assisted Landing Preparations
                IStatus.Planet.AssistedLanding(Event);
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment(object O)
        {
            try
            {                
                IStatus.Fighter.Deployed = false;
                IStatus.Supercruise = false;
                IStatus.Hyperspace = false;
                IStatus.Hardpoints = false;
                IStatus.Touchdown = false;
                IStatus.CargoScoop = false;
                IStatus.LandingGear = false;
                IStatus.WeaponSafety = false;
            }
            catch (Exception ex)
            {
                ExceptionAlignment(Name, ex);
            }
        }
    }
}