//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2019-01-18T08:44:28Z", "event":"ProspectedAsteroid", "Materials":[ { "Name":"HydrogenPeroxide", "Name_Localised":"Hydrogen Peroxide", "Proportion":10.668694 }, { "Name":"water", "Proportion":5.129156 }, { "Name":"liquidoxygen", "Name_Localised":"Liquid oxygen", "Proportion":4.222730 } ], "Content":"$AsteroidMaterialContent_Low;", "Content_Localised":"Material Content: Low", "Remaining":100.000000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_ProspectedAsteroid : Event_Base
    {
        public Event_ProspectedAsteroid()
        {
            Name = "ProspectedAsteroid";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.ProspectedAsteroid((ProspectedAsteroid)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ProspectedAsteroid Event = (ProspectedAsteroid)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables

            #endregion
        }
    }

    #region ProspectedAsteroid Event
    public class ProspectedAsteroid : Base
    {
        public List<Material> Materials { get; set; }
        public string Content { get; set; }
        public string Content_Localised { get; set; }
        public decimal Remaining { get; set; }

        public ProspectedAsteroid()
        {
            Content = Default.String;
            Content_Localised = Default.String;
            Remaining = Default.Decimal;
        }

        public class Material
        {
            public string Name { get; set; }
            public string Name_Localised { get; set; }
            public decimal Proportion { get; set; }

            public Material()
            {
                Name = Default.String;
                Name_Localised = Default.String;
                Proportion = Default.Decimal;
            }
        }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == "ProspectedAsteroid")
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ProspectedAsteroid>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.ProspectedAsteroid.Logic();
// }
