//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-19T04:10:58Z", "event":"LaunchDrone", "Type":"Collection" }

using ALICE_Core;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class ASDF_LaunchDrone : Base
    {
        public string Type { get; set; }

        //Default Constructor
        public ASDF_LaunchDrone()
        {
            Type = Str();
        }
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class QWER_LaunchDrone : Event
    {
        //Variable Generation
        public override void Generate(object O)
        {
            try
            {
                var Event = (LaunchDrone)O;

                Variables.Record(Name + "_Type", Event.Type);
            }
            catch (Exception ex)
            {
                ExceptionGenerate(ex);
            }
        }

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                var Event = (LaunchDrone)O;
            }
            catch (Exception ex)
            {
                ExceptionProcess(ex);
            }
        }

        //Plugin Property Aligment
        public override void Alignment()
        {
            IStatus.Supercruise = false;
            IStatus.Hyperspace = false;
            IStatus.Touchdown = false;
            IStatus.Docking.Docked = false;
        }
    }
}