//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-09T20:09:10Z", "event":"ModuleStore", "MarketID":3221503744, "Slot":"Slot04_Size6", "StoredItem":"$int_hullreinforcement_size5_class2_name;", "StoredItem_Localised":"Hull Reinforcement", "Ship":"federation_corvette", "ShipID":11, "Hot":false, "EngineerModifications":"HullReinforcement_HeavyDuty", "Level":3, "Quality":0.000000 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ModuleStore : Event_Base
    {
        public Event_ModuleStore()
        {
            Name = "ModuleStore";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleStore Event = (ModuleStore)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.Variable());
            Variable_Craft("Slot", Event.Slot.Variable());
            Variable_Craft("StoredItem", Event.StoredItem.Variable());
            Variable_Craft("StoredItem_Localised", Event.StoredItem_Localised.Variable());
            Variable_Craft("Ship", Event.Ship.Variable());
            Variable_Craft("ShipID", Event.ShipID.Variable());
            Variable_Craft("Hot", Event.Hot.Variable());
            Variable_Craft("EngineerModifications", Event.EngineerModifications.Variable());
            Variable_Craft("Level", Event.Level.Variable());
            Variable_Craft("Quality", Event.Quality.Variable());
            #endregion
        }
    }

    #region ModuleStore Event
    public class ModuleStore : Base
    {
        public decimal MarketID { get; set; }
        public string Slot { get; set; }
        public string StoredItem { get; set; }
        public string StoredItem_Localised { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
        public string Hot { get; set; }
        public string EngineerModifications { get; set; }
        public decimal Level { get; set; }
        public decimal Quality { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == ModuleStore)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleStore>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
