//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/12/2018 1:27 AM
//Source Journal Line: { "timestamp":"2018-10-30T04:08:50Z", "event":"ModuleSell", "MarketID":3223901184, "Slot":"Slot03_Size7", "SellItem":"$int_hullreinforcement_size5_class2_name;", "SellItem_Localised":"Hull Reinforcement", "SellPrice":450000, "Ship":"federation_corvette", "ShipID":11 }

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ALICE_Objects;
using ALICE_Internal;

namespace ALICE_Events
{
    public class Event_ModuleSell : Event_Base
    {
        public Event_ModuleSell()
        {
            Name = "ModuleSell";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            //Custom Logic Here.

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            ModuleSell Event = (ModuleSell)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("MarketID", Event.MarketID.Variable());
            Variable_Craft("Slot", Event.Slot.Variable());
            Variable_Craft("SellItem", Event.SellItem.Variable());
            Variable_Craft("SellItem_Localised", Event.SellItem_Localised.Variable());
            Variable_Craft("SellPrice", Event.SellPrice.Variable());
            Variable_Craft("Ship", Event.Ship.Variable());
            Variable_Craft("ShipID", Event.ShipID.Variable());
            #endregion
        }
    }

    #region ModuleSell Event
    public class ModuleSell : Base
    {
        public decimal MarketID { get; set; }
        public string Slot { get; set; }
        public string SellItem { get; set; }
        public string SellItem_Localised { get; set; }
        public decimal SellPrice { get; set; }
        public string Ship { get; set; }
        public decimal ShipID { get; set; }
    }
    #endregion
}

//Journal Reader Code Chunk.

// else if (EventName == ModuleSell)
// {
//     var Event = JsonConvert.DeserializeObject<ALICE_Events.ModuleSell>(RawLine);
//     IEvents.UpdateEvents(EventName, Event);
//     IEvents.Bounty.Logic();
// }
