//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/20/2018 12:20 AM
//Source Journal Line: (Custom A.L.I.C.E Event)

using ALICE_Debug;
using ALICE_Response;
using ALICE_Status;
using System;

namespace ALICE_Events
{
    /// <summary>
    /// Object Data Class
    /// </summary>
    public class FuelLow : Base
    {
        //No Properties
    }

    /// <summary>
    /// Event Logic & Data Storage Class
    /// </summary>
    public class Event_FuelLow : Event
    {
        //Event Instance
        public FuelLow I { get; set; } = new FuelLow();

        //Plugin Logic Process
        public override void Process(object O)
        {
            try
            {
                //Audio - FuelLow
                IResponse.Fuel.Low(
                    ICheck.Initialized(ClassName),                      //Check Plugin Initialized
                    ICheck.InitializedStatus(ClassName),                //Check Status.Json Initialized
                    ICheck.Status.FuelScooping(ClassName, false));      //Check Not Fuel Scooping     

                //Update Status Object
                IStatus.Fuel.Low = true;
            }
            catch (Exception ex)
            {
                ExceptionProcess(Name, ex);
            }
        }
    }
}