//Code Generated By Project A.L.I.C.E Developer Toolkit
//Class File Generated: 11/20/2018 12:20 AM
//Source Journal Line: (Custom A.L.I.C.E Event)
//Reference Journal Line: { "timestamp":"2016-06-10T14:32:03Z", "event":"CommitCrime", "CrimeType":"assault", "Faction":"The Pilots Federation", "Victim":"Potapinski", "Bounty":210 }
//Reference Journal Line: { "timestamp":"2018-11-22T16:58:32Z", "event":"CommitCrime", "CrimeType":"assault", "Faction":"Independent Detention Foundation", "Victim":"The Heart of Orion", "Bounty":300 }

using System;
using ALICE_Internal;
using ALICE_EventLogic;

namespace ALICE_Events
{
    public class Event_Assult : Event_Base
    {
        public Event_Assult()
        {
            Name = "Assult";
        }

        public void Logic()
        {
            if (IEvents.WriteVariables && WriteVariables)
            {
                try
                {
                    Variables_Clear();
                    Variables_Generate();
                    Variables_Write();
                }
                catch (Exception ex)
                {
                    Logger.Exception(Name, "An Exception Occured While Updating Variables");
                    Logger.Exception(Name, "Exception: " + ex);
                }
            }

            Process.Assult((Assult)GetEvent());

            TriggerEvent();
        }

        public void Variables_Generate()
        {
            Assult Event = (Assult)IEvents.GetEvent(Name);

            Variables.Clear();

            #region Custom Variables

            #endregion

            #region Event Variables
            Variable_Craft("Faction", Event.Faction.ToString());
            Variable_Craft("Victim", Event.Victim.ToString());
            Variable_Craft("Amount", Event.Amount.ToString());
            Variable_Craft("Charge", Event.Charge.ToString());
            #endregion
        }

        public void Construct(CommitCrime Event)
        {
            Assult Temp = new Assult()
            {
                Charge = "Bounty",
                Faction = Event.Faction,
                Victim = Event.Victim,
                Amount = Event.Bounty
            };

            UpdateEvents(Name, Temp);
            Logic();
        }
    }

    #region Assult Event
    public class Assult : Base
    {
        public string Violation { get; set; }
        public string Victim { get; set; }
        public string Faction { get; set; }
        public string Charge { get; set; }
        public decimal Amount { get; set; }
    }
    #endregion
}
